cargo-features = ["edition2021"]

[package]
edition = "2021"
name = "slos-helpers"
version = "0.0.1-dev.1"
license = "BSD-2-Clause-Patent"

[features]
std = [ ]
default = [ ]

[dependencies]
array-init = "2.0"
