name: GitHub Pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
      - uses: arcnmx/ci/actions/nix/install@master
      - name: Run "cargo --version && rustc --version"
        run: nix-shell --command "cargo --version && rustc --version"

      - name: Run "cargo doc --workspace --no-deps"
        run: nix-shell --command "cargo doc --workspace --no-deps"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
